### ISSUE TITLE
Create Menu

### ISSUE THREAD

**Issue by nguyenthinhhn** [nguyenthinhhn/html-profile#18]
Create Menu and profile
![image](https://user-images.githubusercontent.com/40859990/94893152-b0173c00-04b0-11eb-9211-a54d2a8df160.png)

**Comment by js899** [comment]
Do you want only frontend part ? Any specific technologies ?

**Comment by nguyenthinhhn** [comment]
> Do you want only frontend part ? Any specific technologies ?
yes.

**Comment by js899** [comment]
And could it look some different than what's in the image ?

**Comment by nguyenthinhhn** [comment]
yes. you can do it differently, but that's basically it

**Comment by js899** [comment]
you have closed the issue. should i not work on it now ?
