### ISSUE TITLE
Form contact and map

### ISSUE THREAD

**Issue by nguyenthinhhn** [nguyenthinhhn/html-profile#22]
![image](https://user-images.githubusercontent.com/40859990/94894011-ad1d4b00-04b2-11eb-9f08-0373b0cbe0f5.png)

**Comment by JunaidJaved248** [comment]
@nguyenthinhhn Can you please elaborate me much more what you want to do, because i want to contribute it

**Comment by nguyenthinhhn** [comment]
@JunaidJaved248  You can do as in the image above, the left is a random map, the right is a form
