### ISSUE TITLE
Add multiple default avatar

### ISSUE THREAD

**Issue by nguyenthinhhn** [nguyenthinhhn/html-profile#32]
![Screenshot from 2020-10-02 15-36-22](https://user-images.githubusercontent.com/40859990/94904247-3a699b00-04c5-11eb-9dcd-bb29f4bcb9cd.png)

**Comment by ngdangtu-vn** [comment]
Excuse me, what are you trying to do? And can I help?

**Comment by penaxr** [comment]
Will be doing it !
